/*
 * test_crypto.c - conformance and adversarial tests for the relay crypto core.
 *
 * Every expected value comes from tests/vectors.json, which is generated by
 * Node's audited crypto module (protocol/tools/generate-vectors.mjs). The Dart
 * client asserts the same file, so a passing run here means the two sides agree
 * byte for byte.
 *
 * Usage: test_crypto.exe [path/to/vectors.json]
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "../common/crypto/dsh_aes.h"
#include "../common/crypto/dsh_sha256.h"
#include "../common/json/dsh_json.h"
#include "../common/wire/dsh_wire.h"

static int failures = 0;
static int checks = 0;

static void check(int condition, const char *what) {
    checks++;
    if (!condition) {
        failures++;
        printf("  FAIL %s\n", what);
    }
}

static int unhex(const char *hex, uint8_t *out, size_t out_cap, size_t *out_len) {
    size_t len;
    size_t i;

    if (hex == NULL) {
        return -1;
    }
    len = strlen(hex);
    if ((len % 2) != 0 || len / 2 > out_cap) {
        return -1;
    }
    for (i = 0; i < len / 2; i++) {
        unsigned value = 0;
        int j;
        for (j = 0; j < 2; j++) {
            char c = hex[i * 2 + j];
            unsigned digit;
            if (c >= '0' && c <= '9') digit = (unsigned)(c - '0');
            else if (c >= 'a' && c <= 'f') digit = (unsigned)(c - 'a' + 10);
            else if (c >= 'A' && c <= 'F') digit = (unsigned)(c - 'A' + 10);
            else return -1;
            value = (value << 4) | digit;
        }
        out[i] = (uint8_t)value;
    }
    *out_len = len / 2;
    return 0;
}

static void hexify(const uint8_t *data, size_t len, char *out, size_t out_cap) {
    static const char digits[] = "0123456789abcdef";
    size_t i;
    if (out_cap < len * 2 + 1) {
        out[0] = '\0';
        return;
    }
    for (i = 0; i < len; i++) {
        out[i * 2] = digits[data[i] >> 4];
        out[i * 2 + 1] = digits[data[i] & 0xf];
    }
    out[len * 2] = '\0';
}

static char *read_file(const char *path, size_t *len_out) {
    FILE *fp = fopen(path, "rb");
    long size;
    char *buffer;

    if (fp == NULL) {
        return NULL;
    }
    fseek(fp, 0, SEEK_END);
    size = ftell(fp);
    fseek(fp, 0, SEEK_SET);
    if (size <= 0) {
        fclose(fp);
        return NULL;
    }
    buffer = (char *)malloc((size_t)size + 1);
    if (buffer == NULL) {
        fclose(fp);
        return NULL;
    }
    if (fread(buffer, 1, (size_t)size, fp) != (size_t)size) {
        free(buffer);
        fclose(fp);
        return NULL;
    }
    buffer[size] = '\0';
    fclose(fp);
    *len_out = (size_t)size;
    return buffer;
}

int main(int argc, char **argv) {
    const char *vectors_path = (argc > 1) ? argv[1] : "tests/vectors.json";
    char *text;
    size_t text_len = 0;
    dsh_json *root;
    const dsh_json *list;
    size_t i;

    /* Unbuffered so a crash never swallows the progress already printed. */
    setvbuf(stdout, NULL, _IONBF, 0);

    printf("dsh relay crypto conformance\n");
    printf("vectors: %s\n\n", vectors_path);

    text = read_file(vectors_path, &text_len);
    if (text == NULL) {
        printf("cannot read %s (run: node protocol/tools/generate-vectors.mjs)\n", vectors_path);
        return 2;
    }
    root = dsh_json_parse(text, text_len);
    if (root == NULL) {
        printf("vectors file is not valid JSON\n");
        free(text);
        return 2;
    }

    /* ── SHA-256 ─────────────────────────────────────────────────────────── */
    printf("sha256\n");
    list = dsh_json_get(root, "sha256Vectors");
    for (i = 0; list != NULL && i < list->u.arr.count; i++) {
        const dsh_json *item = list->u.arr.items[i];
        size_t in_len = 0;
        const char *input = dsh_json_string(dsh_json_get(item, "input"), "", &in_len);
        const char *expect = dsh_json_string(dsh_json_get(item, "expect"), "", NULL);
        uint8_t digest[DSH_SHA256_DIGEST_LEN];
        char got[DSH_SHA256_DIGEST_LEN * 2 + 1];

        dsh_sha256(input, in_len, digest);
        hexify(digest, sizeof(digest), got, sizeof(got));
        check(strcmp(got, expect) == 0, "sha256 digest");
        if (strcmp(got, expect) != 0) {
            printf("    len=%zu\n    got=%s\n    exp=%s\n", in_len, got, expect);
        }
    }

    /* ── HMAC-SHA256 ─────────────────────────────────────────────────────── */
    printf("hmac-sha256\n");
    list = dsh_json_get(root, "hmacVectors");
    for (i = 0; list != NULL && i < list->u.arr.count; i++) {
        const dsh_json *item = list->u.arr.items[i];
        const char *key_hex = dsh_json_string(dsh_json_get(item, "keyHex"), "", NULL);
        const char *data_hex = dsh_json_string(dsh_json_get(item, "dataHex"), "", NULL);
        const char *expect = dsh_json_string(dsh_json_get(item, "expect"), "", NULL);
        uint8_t key[512];
        uint8_t data[512];
        size_t key_len = 0;
        size_t data_len = 0;
        uint8_t mac[DSH_SHA256_DIGEST_LEN];
        char got[DSH_SHA256_DIGEST_LEN * 2 + 1];

        check(unhex(key_hex, key, sizeof(key), &key_len) == 0, "hmac key hex");
        check(unhex(data_hex, data, sizeof(data), &data_len) == 0, "hmac data hex");
        dsh_hmac_sha256(key, key_len, data, data_len, mac);
        hexify(mac, sizeof(mac), got, sizeof(got));
        check(strcmp(got, expect) == 0, "hmac digest");
        if (strcmp(got, expect) != 0) {
            printf("    got=%s\n    exp=%s\n", got, expect);
        }
    }

    /* ── PBKDF2 ──────────────────────────────────────────────────────────── */
    printf("pbkdf2-hmac-sha256\n");
    list = dsh_json_get(root, "pbkdf2Vectors");
    for (i = 0; list != NULL && i < list->u.arr.count; i++) {
        const dsh_json *item = list->u.arr.items[i];
        const char *pass_hex = dsh_json_string(dsh_json_get(item, "passHex"), "", NULL);
        const char *salt_hex = dsh_json_string(dsh_json_get(item, "saltHex"), "", NULL);
        const char *expect = dsh_json_string(dsh_json_get(item, "expect"), "", NULL);
        uint32_t iterations = (uint32_t)dsh_json_integer(dsh_json_get(item, "iterations"), 1);
        size_t dk_len = (size_t)dsh_json_integer(dsh_json_get(item, "dkLen"), 32);
        uint8_t pass[256];
        uint8_t salt[256];
        size_t pass_len = 0;
        size_t salt_len = 0;
        uint8_t derived[128];
        char got[257];

        check(unhex(pass_hex, pass, sizeof(pass), &pass_len) == 0, "pbkdf2 pass hex");
        check(unhex(salt_hex, salt, sizeof(salt), &salt_len) == 0, "pbkdf2 salt hex");
        if (dk_len > sizeof(derived)) {
            dk_len = sizeof(derived);
        }

        dsh_pbkdf2_hmac_sha256(pass, pass_len, salt, salt_len, iterations, derived, dk_len);
        hexify(derived, dk_len, got, sizeof(got));
        check(strcmp(got, expect) == 0, "pbkdf2 derived key");
        if (strcmp(got, expect) != 0) {
            printf("    iters=%u dkLen=%zu\n    got=%s\n    exp=%s\n", iterations, dk_len, got, expect);
        }
    }

    /* ── AES-256 block ───────────────────────────────────────────────────── */
    printf("aes-256 block\n");
    list = dsh_json_get(root, "aesBlockVectors");
    for (i = 0; list != NULL && i < list->u.arr.count; i++) {
        const dsh_json *item = list->u.arr.items[i];
        const char *key_hex = dsh_json_string(dsh_json_get(item, "keyHex"), "", NULL);
        const char *plain_hex = dsh_json_string(dsh_json_get(item, "plainHex"), "", NULL);
        const char *expect = dsh_json_string(dsh_json_get(item, "expectCipher"), "", NULL);
        uint8_t key[32];
        uint8_t plain[16];
        uint8_t cipher[16];
        uint8_t back[16];
        size_t key_len = 0;
        size_t plain_len = 0;
        dsh_aes256 aes;
        char got[33];

        check(unhex(key_hex, key, sizeof(key), &key_len) == 0 && key_len == 32, "aes key hex");
        check(unhex(plain_hex, plain, sizeof(plain), &plain_len) == 0 && plain_len == 16, "aes plain hex");

        dsh_aes256_init(&aes, key);
        dsh_aes256_encrypt_block(&aes, plain, cipher);
        hexify(cipher, sizeof(cipher), got, sizeof(got));
        check(strcmp(got, expect) == 0, "aes-256 encrypt block (FIPS-197 C.3)");
        if (strcmp(got, expect) != 0) {
            printf("    got=%s\n    exp=%s\n", got, expect);
        }

        dsh_aes256_decrypt_block(&aes, cipher, back);
        check(memcmp(back, plain, 16) == 0, "aes-256 decrypt block round trip");
    }

    /* ── AES-256-CBC with PKCS#7 ─────────────────────────────────────────── */
    printf("aes-256-cbc/pkcs7\n");
    list = dsh_json_get(root, "cbcVectors");
    for (i = 0; list != NULL && i < list->u.arr.count; i++) {
        const dsh_json *item = list->u.arr.items[i];
        const char *key_hex = dsh_json_string(dsh_json_get(item, "keyHex"), "", NULL);
        const char *iv_hex = dsh_json_string(dsh_json_get(item, "ivHex"), "", NULL);
        const char *plain_hex = dsh_json_string(dsh_json_get(item, "plainHex"), "", NULL);
        const char *expect = dsh_json_string(dsh_json_get(item, "cipherHex"), "", NULL);
        uint8_t key[32];
        uint8_t iv[16];
        size_t key_len = 0;
        size_t iv_len = 0;
        size_t plain_len = 0;
        uint8_t *plain;
        size_t plain_cap;
        uint8_t *cipher;
        uint8_t *back;
        size_t cipher_len = 0;
        size_t back_len = 0;
        dsh_aes256 aes;
        char *got;

        check(unhex(key_hex, key, sizeof(key), &key_len) == 0 && key_len == 32, "cbc key hex");
        check(unhex(iv_hex, iv, sizeof(iv), &iv_len) == 0 && iv_len == 16, "cbc iv hex");

        plain_cap = strlen(plain_hex) / 2;
        plain = (uint8_t *)malloc(plain_cap + 1);
        cipher = (uint8_t *)malloc(plain_cap + 32);
        back = (uint8_t *)malloc(plain_cap + 32);
        got = (char *)malloc(strlen(expect) + 1);
        if (plain == NULL || cipher == NULL || back == NULL || got == NULL) {
            printf("  FAIL allocation\n");
            failures++;
            free(plain); free(cipher); free(back); free(got);
            continue;
        }

        check(unhex(plain_hex, plain, plain_cap, &plain_len) == 0, "cbc plain hex");
        if (plain_len == 0) {
            /* An empty plaintext is a legitimate vector; unhex reports length 0. */
            plain_len = 0;
        }

        dsh_aes256_init(&aes, key);
        dsh_aes256_cbc_encrypt(&aes, iv, plain, plain_len, cipher, &cipher_len);
        hexify(cipher, cipher_len, got, strlen(expect) + 1);
        check(strcmp(got, expect) == 0, "cbc ciphertext");
        if (strcmp(got, expect) != 0) {
            printf("    note=%s\n    got=%s\n    exp=%s\n",
                   dsh_json_string(dsh_json_get(item, "note"), "?", NULL), got, expect);
        }

        check(dsh_aes256_cbc_decrypt(&aes, iv, cipher, cipher_len, back, &back_len) == 0,
              "cbc decrypt returns 0");
        check(back_len == plain_len, "cbc decrypt length");
        check(memcmp(back, plain, plain_len) == 0, "cbc decrypt round trip");

        free(plain);
        free(cipher);
        free(back);
        free(got);
    }

    /* ── key derivation matches the recorded master material ─────────────── */
    printf("session key derivation\n");
    {
        const dsh_json *frame = dsh_json_get(root, "frameVector");
        if (frame != NULL) {
            /*
             * Read the round count from the file rather than repeating it, so
             * changing the protocol's iteration count is a one-line edit in the
             * generator and nothing here can silently disagree with it.
             */
            uint32_t kdf_iterations = (uint32_t)dsh_json_integer(
                dsh_json_get(dsh_json_get(root, "kdf"), "iterations"), 50000);
            const char *passphrase = dsh_json_string(dsh_json_get(frame, "passphrase"), "", NULL);
            const char *salt_hex = dsh_json_string(dsh_json_get(frame, "salt"), "", NULL);
            const char *cnonce_hex = dsh_json_string(dsh_json_get(frame, "clientNonce"), "", NULL);
            const char *snonce_hex = dsh_json_string(dsh_json_get(frame, "serverNonce"), "", NULL);
            const char *expect_master = dsh_json_string(dsh_json_get(frame, "masterHex"), "", NULL);
            const char *expect_c2s = dsh_json_string(dsh_json_get(frame, "keyC2sHex"), "", NULL);
            const char *expect_s2c = dsh_json_string(dsh_json_get(frame, "keyS2cHex"), "", NULL);
            uint8_t salt[16];
            uint8_t cnonce[16];
            uint8_t snonce[16];
            size_t got_len = 0;
            uint8_t mixed[48];
            uint8_t master[64];
            uint8_t key_c2s[32];
            uint8_t key_s2c[32];
            char got[129];
            static const uint8_t label_c2s[4] = { 'c', '2', 's', 0 };
            static const uint8_t label_s2c[4] = { 's', '2', 'c', 0 };

            check(unhex(salt_hex, salt, sizeof(salt), &got_len) == 0 && got_len == 16, "salt hex");
            check(unhex(cnonce_hex, cnonce, sizeof(cnonce), &got_len) == 0 && got_len == 16, "client nonce hex");
            check(unhex(snonce_hex, snonce, sizeof(snonce), &got_len) == 0 && got_len == 16, "server nonce hex");

            memcpy(mixed, salt, 16);
            memcpy(mixed + 16, cnonce, 16);
            memcpy(mixed + 32, snonce, 16);

            dsh_pbkdf2_hmac_sha256((const uint8_t *)passphrase, strlen(passphrase),
                                   mixed, sizeof(mixed), kdf_iterations, master, sizeof(master));
            hexify(master, sizeof(master), got, sizeof(got));
            check(strcmp(got, expect_master) == 0, "master secret matches node");
            if (strcmp(got, expect_master) != 0) {
                printf("    got=%s\n    exp=%s\n", got, expect_master);
            }

            dsh_hmac_sha256(master, sizeof(master), label_c2s, sizeof(label_c2s), key_c2s);
            hexify(key_c2s, sizeof(key_c2s), got, sizeof(got));
            check(strcmp(got, expect_c2s) == 0, "client to server key matches node");

            dsh_hmac_sha256(master, sizeof(master), label_s2c, sizeof(label_s2c), key_s2c);
            hexify(key_s2c, sizeof(key_s2c), got, sizeof(got));
            check(strcmp(got, expect_s2c) == 0, "server to client key matches node");
        }
    }

    /* ── end-to-end seal/open, plus tamper and replay rejection ──────────── */
    printf("frame seal/open\n");
    {
        const dsh_json *frame = dsh_json_get(root, "frameVector");
        const char *passphrase = dsh_json_string(dsh_json_get(frame, "passphrase"), "", NULL);
        uint8_t salt[16];
        uint8_t cnonce[16];
        uint8_t snonce[16];
        size_t got_len = 0;
        dsh_crypto sender;
        dsh_crypto server;
        dsh_sb wire;
        uint8_t plain[4096];
        size_t plain_len = 0;
        uint8_t type = 0;
        uint32_t seq = 0;
        const char *message = "{\"t\":\"request\",\"id\":\"r-1\",\"p\":{\"method\":\"session/list\"}}";

        unhex(dsh_json_string(dsh_json_get(frame, "salt"), "", NULL), salt, sizeof(salt), &got_len);
        unhex(dsh_json_string(dsh_json_get(frame, "clientNonce"), "", NULL), cnonce, sizeof(cnonce), &got_len);
        unhex(dsh_json_string(dsh_json_get(frame, "serverNonce"), "", NULL), snonce, sizeof(snonce), &got_len);

        check(dsh_crypto_derive(&sender, passphrase, salt, cnonce, snonce, 0) == 0, "sender derive");
        check(dsh_crypto_derive(&server, passphrase, salt, cnonce, snonce, 1) == 0, "server derive");

        dsh_sb_init(&wire);
        check(dsh_wire_seal(&sender, DSH_FRAME_DATA, message, strlen(message), &wire) == 0, "seal");
        if (wire.buf == NULL) {
            /* A failed seal must not be dereferenced below. */
            check(0, "seal produced no frame");
            dsh_sb_free(&wire);
            dsh_crypto_wipe(&sender);
            dsh_crypto_wipe(&server);
            goto frame_done;
        }

        check(wire.len == DSH_FRAME_HEADER_LEN +
                          ((strlen(message) / 16) + 1) * 16 + DSH_FRAME_TAG_LEN,
              "sealed frame length");
        check(memcmp(wire.buf, "DSHX", 4) == 0, "frame magic");
        check((uint8_t)wire.buf[4] == DSH_WIRE_VERSION, "frame version");
        check((uint8_t)wire.buf[5] == DSH_FRAME_DATA, "frame type");
        check((uint8_t)wire.buf[8] == 0 && (uint8_t)wire.buf[9] == 0 &&
              (uint8_t)wire.buf[10] == 0 && (uint8_t)wire.buf[11] == 1,
              "first sequence is 1");

        check(dsh_wire_open(&server, (const uint8_t *)wire.buf, wire.len,
                            plain, &plain_len, &type, &seq) == 0, "server opens frame");
        check(plain_len == strlen(message), "plaintext length");
        check(memcmp(plain, message, plain_len) == 0, "plaintext bytes");
        check(type == DSH_FRAME_DATA, "decoded type");

        /* A replayed frame must be refused: the sequence already advanced. */
        check(dsh_wire_open(&server, (const uint8_t *)wire.buf, wire.len,
                            plain, &plain_len, &type, &seq) != 0, "replay rejected");

        /* Flipping one ciphertext bit must fail the MAC before decryption. */
        {
            uint8_t *tampered = (uint8_t *)malloc(wire.len);
            memcpy(tampered, wire.buf, wire.len);
            tampered[DSH_FRAME_HEADER_LEN + 1] ^= 0x01;
            check(dsh_wire_open(&server, tampered, wire.len,
                                plain, &plain_len, &type, &seq) == -2, "ciphertext tamper rejected");
            free(tampered);
        }

        /* Rewriting the header type invalidates the MAC that covers it. */
        {
            uint8_t *tampered = (uint8_t *)malloc(wire.len);
            memcpy(tampered, wire.buf, wire.len);
            tampered[5] = DSH_FRAME_BYE;
            check(dsh_wire_open(&server, tampered, wire.len,
                                plain, &plain_len, &type, &seq) == -2, "header tamper rejected");
            free(tampered);
        }

        /* A peer that used a different passphrase must not derive the same keys. */
        {
            dsh_crypto wrong;
            uint8_t garbage[4096];
            size_t garbage_len = 0;
            check(dsh_crypto_derive(&wrong, "wrong passphrase", salt, cnonce, snonce, 1) == 0,
                  "wrong passphrase derives");
            check(dsh_wire_open(&wrong, (const uint8_t *)wire.buf, wire.len,
                                garbage, &garbage_len, &type, &seq) == -2,
                  "wrong passphrase cannot open the frame");
            dsh_crypto_wipe(&wrong);
        }

        /* A second frame from the same sender must carry the next sequence. */
        dsh_sb_reset(&wire);
        check(dsh_wire_seal(&sender, DSH_FRAME_DATA, message, strlen(message), &wire) == 0, "second seal");
        check((uint8_t)wire.buf[11] == 2, "sequence increments");
        check(dsh_wire_open(&server, (const uint8_t *)wire.buf, wire.len,
                            plain, &plain_len, &type, &seq) == 0, "second frame opens");
        check(seq == 2, "second frame carries sequence 2");

    frame_done:
        dsh_sb_free(&wire);
        dsh_crypto_wipe(&sender);
        dsh_crypto_wipe(&server);
    }

    /* ── handshake frames ────────────────────────────────────────────────── */
    printf("handshake frames\n");
    {
        dsh_sb wire;
        uint8_t buffer[512];
        uint8_t type = 0;
        size_t payload_len = 0;
        const uint8_t *payload = NULL;

        dsh_sb_init(&wire);
        check(dsh_wire_seal_plain(DSH_FRAME_HELLO, "{\"role\":1}", 9, &wire) == 0, "seal plain");
        check(wire.len == DSH_FRAME_HEADER_LEN + 9, "plain frame length");
        check(dsh_wire_open_plain((const uint8_t *)wire.buf, wire.len, &type, &payload, &payload_len) == 0,
              "open plain");
        check(type == DSH_FRAME_HELLO, "plain frame type");
        check(payload_len == 9 && memcmp(payload, "{\"role\":1}", 9) == 0, "plain payload");
        dsh_sb_free(&wire);

        /* Handshake frames must not be accepted as established-channel frames. */
        {
            dsh_crypto crypt;
            uint8_t salt[16] = {0};
            uint8_t cn[16] = {0};
            uint8_t sn[16] = {0};
            uint8_t plain[256];
            size_t plen = 0;
            uint32_t seq = 0;

            dsh_crypto_derive(&crypt, "x", salt, cn, sn, 1);
            dsh_sb_init(&wire);
            dsh_wire_seal_plain(DSH_FRAME_HELLO, "{}", 2, &wire);
            check(dsh_wire_open(&crypt, (const uint8_t *)wire.buf, wire.len,
                                plain, &plen, &type, &seq) != 0,
                  "plain frame rejected on encrypted channel");
            dsh_sb_free(&wire);
            dsh_crypto_wipe(&crypt);
        }

        /* Truncated and oversized frames must be rejected, never parsed. */
        dsh_sb_init(&wire);
        dsh_wire_seal_plain(DSH_FRAME_HELLO, "{}", 2, &wire);
        check(dsh_wire_open_plain((const uint8_t *)wire.buf, 8, &type, &payload, &payload_len) != 0,
              "short frame rejected");
        {
            uint8_t *bad = (uint8_t *)malloc(wire.len);
            memcpy(bad, wire.buf, wire.len);
            bad[0] = 'X';
            check(dsh_wire_open_plain(bad, wire.len, &type, &payload, &payload_len) != 0,
                  "bad magic rejected");
            bad[0] = 'D';
            bad[12] = 0x7f; /* claim a huge body */
            check(dsh_wire_open_plain(bad, wire.len, &type, &payload, &payload_len) != 0,
                  "length mismatch rejected");
            free(bad);
        }
        (void)buffer;
        dsh_sb_free(&wire);
    }

    /* ── passphrase comparison ───────────────────────────────────────────── */
    printf("passphrase comparison\n");
    check(dsh_passphrase_matches("abc", "abc", 3) == 1, "equal passphrase matches");
    check(dsh_passphrase_matches("abc", "abd", 3) == 0, "different passphrase rejected");
    check(dsh_passphrase_matches("abc", "ab", 2) == 0, "prefix rejected");
    check(dsh_passphrase_matches("abc", "abcd", 4) == 0, "extension rejected");
    check(dsh_passphrase_matches("", "", 0) == 1, "empty equals empty");

    dsh_json_free(root);
    free(text);

    printf("\n%d checks, %d failures\n", checks, failures);
    return failures == 0 ? 0 : 1;
}
