import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:client_wear/crypto/aes256_cbc.dart';
import 'package:client_wear/crypto/bytes.dart';
import 'package:client_wear/crypto/dsh_frame.dart';
import 'package:client_wear/crypto/hkdf_style.dart';
import 'package:client_wear/crypto/session_crypto.dart';
import 'package:flutter_test/flutter_test.dart';

/// Fixture provenance
/// ------------------
/// `test/fixtures/vectors.json` is a verbatim copy of the repository-level
/// `tests/vectors.json`, itself generated by `protocol/tools/generate-vectors.mjs`
/// and asserted by the C suite in `tests/test_crypto.c`. That file is the only
/// authority for cross-language agreement, so the copy is checked for drift by
/// the "fixture copy" test below whenever the repository layout is present.
///
/// The copy exists because `flutter test` sets the package directory
/// (`client_wear/`) as its working directory, which makes the parent path
/// awkward to reach from a portable test run.
final Map<String, Object?> _vectors = _loadVectors();

Map<String, Object?> _loadVectors() {
  final file = File('test/fixtures/vectors.json');
  if (!file.existsSync()) {
    fail('missing fixture ${file.absolute.path}; copy tests/vectors.json there');
  }
  return jsonDecode(file.readAsStringSync()) as Map<String, Object?>;
}

List<Map<String, Object?>> _group(String name) =>
    (_vectors[name] as List<Object?>).cast<Map<String, Object?>>();

String _str(Map<String, Object?> row, String key) => row[key] as String;
int _int(Map<String, Object?> row, String key) => (row[key] as num).toInt();

/// The frame vector's keys cost one full 200k round PBKDF2, so every test in
/// this file shares a single derivation.
SessionKeys? _frameKeysCache;
SessionKeys _frameKeys() => _frameKeysCache ??= _deriveFrameKeys();

Map<String, Object?> get _frameVector =>
    _vectors['frameVector'] as Map<String, Object?>;

SessionKeys _deriveFrameKeys() => SessionKeyDerivation.derive(
      passphrase: _str(_frameVector, 'passphrase'),
      serverSalt: Hex.decode(_str(_frameVector, 'salt')),
      clientNonce: Hex.decode(_str(_frameVector, 'clientNonce')),
      serverNonce: Hex.decode(_str(_frameVector, 'serverNonce')),
    );

Uint8List _frameIv() => Hex.decode(_str(_frameVector, 'frameIvHex'));
Uint8List _framePlain() => Hex.decode(_str(_frameVector, 'framePlainHex'));

/// Rebuilds the vector frame through the production sealer with a pinned IV.
Uint8List _sealVectorFrame({bool isServer = false}) {
  final session = SessionCrypto(keys: _frameKeys(), isServer: isServer);
  return session.seal(DshFrameType.data, _framePlain(), iv: _frameIv());
}

Matcher _rejectedWith(DshFrameFailure failure) => throwsA(
      isA<DshFrameException>()
          .having((e) => e.failure, 'failure', failure),
    );

void main() {
  group('fixture copy', () {
    test('matches the canonical tests/vectors.json byte for byte', () {
      final canonical = File('../tests/vectors.json');
      if (!canonical.existsSync()) {
        markTestSkipped('repository vectors.json not reachable from this run');
        return;
      }
      expect(
        File('test/fixtures/vectors.json').readAsBytesSync(),
        canonical.readAsBytesSync(),
        reason: 'the fixture copy drifted from the authoritative vectors',
      );
    });
  });

  group('sha256Vectors', () {
    for (final vector in _group('sha256Vectors')) {
      final input = utf8.encode(_str(vector, 'input'));
      test('${input.length} byte input', () {
        expect(Hex.encode(Digests.sha256(input)), _str(vector, 'expect'));
      });
    }
  });

  group('hmacVectors', () {
    for (final vector in _group('hmacVectors')) {
      final keyText = _str(vector, 'key');
      final dataText = _str(vector, 'data');
      test('key of ${keyText.length} chars, data of ${dataText.length} chars', () {
        expect(Hex.encode(utf8.encode(keyText)), _str(vector, 'keyHex'));
        expect(Hex.encode(utf8.encode(dataText)), _str(vector, 'dataHex'));
        expect(
          Hex.encode(Digests.hmacSha256(utf8.encode(keyText), utf8.encode(dataText))),
          _str(vector, 'expect'),
        );
      });
    }
  });

  group('pbkdf2Vectors', () {
    for (final vector in _group('pbkdf2Vectors')) {
      final passText = _str(vector, 'pass');
      final saltText = _str(vector, 'salt');
      final iterations = _int(vector, 'iterations');
      test('$iterations rounds, ${_int(vector, 'dkLen')} byte output', () {
        expect(Hex.encode(utf8.encode(passText)), _str(vector, 'passHex'));
        expect(Hex.encode(utf8.encode(saltText)), _str(vector, 'saltHex'));
        expect(
          Hex.encode(Digests.pbkdf2HmacSha256(
            password: utf8.encode(passText),
            salt: utf8.encode(saltText),
            iterations: iterations,
            derivedKeyLength: _int(vector, 'dkLen'),
          )),
          _str(vector, 'expect'),
        );
      });
    }
  });

  group('aesBlockVectors', () {
    for (final vector in _group('aesBlockVectors')) {
      test(_str(vector, 'note'), () {
        final key = Hex.decode(_str(vector, 'keyHex'));
        final plain = Hex.decode(_str(vector, 'plainHex'));
        expect(Hex.encode(Aes256Cbc.encryptBlock(key, plain)), _str(vector, 'expectCipher'));
        expect(
          Hex.encode(Aes256Cbc.decryptBlock(key, Hex.decode(_str(vector, 'cipherHex')))),
          _str(vector, 'plainHex'),
        );
      });
    }
  });

  group('cbcVectors', () {
    for (final vector in _group('cbcVectors')) {
      test(_str(vector, 'note'), () {
        final key = Hex.decode(_str(vector, 'keyHex'));
        final iv = Hex.decode(_str(vector, 'ivHex'));
        final plain = Hex.decode(_str(vector, 'plainHex'));
        final cipher = Hex.decode(_str(vector, 'cipherHex'));

        expect(plain.length % 16 == 0 && plain.isNotEmpty
            ? cipher.length
            : Aes256Cbc.cipherLength(plain.length), cipher.length);
        expect(Hex.encode(Aes256Cbc.encrypt(key: key, iv: iv, plaintext: plain)),
            _str(vector, 'cipherHex'));
        expect(Hex.encode(Aes256Cbc.decrypt(key: key, iv: iv, ciphertext: cipher)),
            _str(vector, 'plainHex'));
      });
    }
  });

  group('frameVector: key derivation', () {
    test('master and the four directional keys match the C implementation', () {
      final keys = _frameKeys();
      expect(Hex.encode(keys.master), _str(_frameVector, 'masterHex'));
      expect(Hex.encode(keys.keyC2s), _str(_frameVector, 'keyC2sHex'));
      expect(Hex.encode(keys.keyS2c), _str(_frameVector, 'keyS2cHex'));
      expect(Hex.encode(keys.macC2s), _str(_frameVector, 'macC2sHex'));
      expect(Hex.encode(keys.macS2c), _str(_frameVector, 'macS2cHex'));

      expect(_str(_vectors['kdf']! as Map<String, Object?>, 'saltMaterial'),
          'serverSalt(16) || clientNonce(16) || serverNonce(16)');
      expect(SessionKeyDerivation.iterations,
          _int(_vectors['kdf']! as Map<String, Object?>, 'iterations'));
      expect(SessionKeyDerivation.masterLength,
          _int(_vectors['kdf']! as Map<String, Object?>, 'masterLen'));
    });
  });

  group('frameVector: frame bytes', () {
    test('ciphertext matches frameCipherHex', () {
      expect(
        Hex.encode(Aes256Cbc.encrypt(
          key: _frameKeys().keyC2s,
          iv: _frameIv(),
          plaintext: _framePlain(),
        )),
        _str(_frameVector, 'frameCipherHex'),
      );
    });

    test('header matches frameHeaderHex', () {
      final header = DshFrameHeader.encode(
        type: DshFrameType.data,
        flags: 0,
        sequence: 1,
        bodyLength: Hex.decode(_str(_frameVector, 'frameCipherHex')).length,
        iv: _frameIv(),
      );
      expect(Hex.encode(header), _str(_frameVector, 'frameHeaderHex'));
    });

    test('tag matches frameTagHex', () {
      final cipher = Hex.decode(_str(_frameVector, 'frameCipherHex'));
      final signed = concatBytes([
        Hex.decode(_str(_frameVector, 'frameHeaderHex')),
        cipher,
      ]);
      expect(Hex.encode(Digests.hmacSha256(_frameKeys().macC2s, signed)),
          _str(_frameVector, 'frameTagHex'));
    });

    test('the sealed frame equals frameTotalHex', () {
      expect(Hex.encode(_sealVectorFrame()), _str(_frameVector, 'frameTotalHex'));
    });

    test('frame length obeys 32 + ciphertext + 32', () {
      final frame = _sealVectorFrame();
      final cipherLength = Hex.decode(_str(_frameVector, 'frameCipherHex')).length;
      expect(frame.length, 32 + cipherLength + 32);
      expect(frame.length, Hex.decode(_str(_frameVector, 'frameTotalHex')).length);
    });
  });

  group('frameVector: round trip and rejections', () {
    test('the server role opens the client sealed frame', () {
      final server = SessionCrypto(keys: _frameKeys(), isServer: true);
      final opened = server.open(_sealVectorFrame());
      expect(opened.type, DshFrameType.data);
      expect(opened.sequence, 1);
      expect(opened.payload, _framePlain());
      expect(opened.text, _str(_frameVector, 'framePlainText'));
      expect(server.receiveSequence, 1);
      expect(server.sendSequence, 1);
    });

    test('a replayed frame is rejected', () {
      final server = SessionCrypto(keys: _frameKeys(), isServer: true);
      final frame = _sealVectorFrame();
      server.open(frame);
      expect(() => server.open(frame), _rejectedWith(DshFrameFailure.replay));
      expect(server.receiveSequence, 1, reason: 'a replay must not advance the window');
    });

    test('an out of order older sequence is rejected', () {
      final server = SessionCrypto(keys: _frameKeys(), isServer: true);
      final sender = SessionCrypto(keys: _frameKeys());
      final first = sender.seal(DshFrameType.data, utf8.encode('one'));
      final second = sender.seal(DshFrameType.data, utf8.encode('two'));
      expect(server.open(second).text, 'two');
      expect(() => server.open(first), _rejectedWith(DshFrameFailure.replay));
    });

    test('flipping one ciphertext bit fails the MAC, not the padding', () {
      final server = SessionCrypto(keys: _frameKeys(), isServer: true);
      final frame = _sealVectorFrame();
      final tampered = Uint8List.fromList(frame);
      tampered[40] ^= 0x01; // inside the ciphertext region [32, 32 + N)
      expect(() => server.open(tampered), _rejectedWith(DshFrameFailure.tampered));
      expect(server.receiveSequence, 0);
    });

    test('flipping one tag bit fails the MAC', () {
      final server = SessionCrypto(keys: _frameKeys(), isServer: true);
      final frame = _sealVectorFrame();
      final tampered = Uint8List.fromList(frame);
      tampered[tampered.length - 1] ^= 0x80;
      expect(() => server.open(tampered), _rejectedWith(DshFrameFailure.tampered));
    });

    test('rewriting the sequence in the header fails the MAC', () {
      final server = SessionCrypto(keys: _frameKeys(), isServer: true);
      final tampered = Uint8List.fromList(_sealVectorFrame());
      tampered[11] = 9; // sequence byte
      expect(() => server.open(tampered), _rejectedWith(DshFrameFailure.tampered));
    });

    test('a corrupted magic or version is malformed', () {
      final server = SessionCrypto(keys: _frameKeys(), isServer: true);
      final frame = _sealVectorFrame();

      final badMagic = Uint8List.fromList(frame)..[0] = 0x00;
      expect(() => server.open(badMagic), _rejectedWith(DshFrameFailure.malformed));

      final badVersion = Uint8List.fromList(frame)..[4] = 2;
      expect(() => server.open(badVersion), _rejectedWith(DshFrameFailure.malformed));

      expect(() => server.open(frame.sublist(0, 63)),
          _rejectedWith(DshFrameFailure.malformed));
      expect(server.receiveSequence, 0);
    });

    test('a handshake frame is refused on an established channel', () {
      final server = SessionCrypto(keys: _frameKeys(), isServer: true);
      expect(
        () => server.open(DshPlainFrame.seal(DshFrameType.hello, utf8.encode('{}'))),
        _rejectedWith(DshFrameFailure.malformed),
      );
    });

    test('the wrong passphrase cannot open the session', () {
      final wrong = SessionCrypto(
        keys: SessionKeyDerivation.derive(
          passphrase: 'wrong passphrase',
          serverSalt: Hex.decode(_str(_frameVector, 'salt')),
          clientNonce: Hex.decode(_str(_frameVector, 'clientNonce')),
          serverNonce: Hex.decode(_str(_frameVector, 'serverNonce')),
          iterations: 1000, // iteration count only affects key bytes, not the check
        ),
        isServer: true,
      );
      expect(() => wrong.open(_sealVectorFrame()), _rejectedWith(DshFrameFailure.tampered));
    });

    test('both roles round trip arbitrary payloads and advance the sequence', () {
      final client = SessionCrypto(keys: _frameKeys());
      final server = SessionCrypto(keys: _frameKeys(), isServer: true);

      for (var i = 0; i < 4; i++) {
        final payload = utf8.encode('payload-$i');
        final sealed = client.seal(DshFrameType.data, payload);
        final opened = server.open(sealed);
        expect(opened.sequence, i + 1);
        expect(opened.payload, payload);

        final reply = server.seal(DshFrameType.data, utf8.encode('reply-$i'));
        expect(client.open(reply).payload, utf8.encode('reply-$i'));
      }
      expect(client.sendSequence, 5);
      expect(server.sendSequence, 5);
    });

    test('a block aligned payload still grows by one padding block', () {
      final client = SessionCrypto(keys: _frameKeys());
      final server = SessionCrypto(keys: _frameKeys(), isServer: true);
      final payload = Uint8List(32);
      final sealed = client.seal(DshFrameType.data, payload);
      expect(sealed.length, 32 + 48 + 32);
      expect(server.open(sealed).payload, payload);

      final empty = client.seal(DshFrameType.data, const <int>[]);
      expect(empty.length, 32 + 16 + 32);
      expect(server.open(empty).payload, isEmpty);
    });
  });

  group('handshake frames', () {
    test('a plaintext frame has flags bit 0, a zero sequence and no tag', () {
      final body = utf8.encode('{"role":2}');
      final frame = DshPlainFrame.seal(DshFrameType.hello, body);
      expect(frame.length, 32 + body.length);
      expect(frame.sublist(0, 4), DshFrameLayout.magic);
      expect(frame[4], 1);
      expect(frame[5], DshFrameType.hello);
      expect(frame[6] & 0x01, 0x01);
      expect(Hex.encode(frame.sublist(12, 16)),
          Hex.encode([0, 0, 0, body.length]));
      expect(Hex.encode(frame.sublist(16, 32)), '0' * 32);

      final parsed = DshPlainFrame.parse(frame);
      expect(parsed.type, DshFrameType.hello);
      expect(parsed.payload, body);
    });

    test('the proof is HMAC(passphrase, "dsh-relay/v1" || nonce)', () {
      final nonce = Hex.decode('00112233445566778899aabbccddeeff');
      const passphrase = 'correct horse battery staple';
      expect(
        Hex.encode(SessionKeyDerivation.handshakeProof(passphrase, nonce)),
        Hex.encode(Digests.hmacSha256(
          utf8.encode(passphrase),
          concatBytes([utf8.encode('dsh-relay/v1'), nonce]),
        )),
      );
    });

    test('HELLO survives a JSON round trip and verifies its proof', () {
      final nonce = Hex.decode('0f1e2d3c4b5a69788796a5b4c3d2e1f0');
      final hello = DshHello.create(
        role: DshRole.client,
        name: 'wear-watch',
        passphrase: 'correct horse battery staple',
        nonce: nonce,
      );
      final encoded = hello.encode();
      expect(jsonDecode(encoded), <String, Object?>{
        'role': 2,
        'name': 'wear-watch',
        'nonce': '0f1e2d3c4b5a69788796a5b4c3d2e1f0',
        'proof': Hex.encode(hello.proof),
      });
      expect(hello.proof.length, 32);
      expect(hello.nonce.length, 16);

      final parsed = DshHello.parse(encoded);
      expect(parsed.role, DshRole.client);
      expect(parsed.name, 'wear-watch');
      expect(parsed.matchesPassphrase('correct horse battery staple'), isTrue);
      expect(parsed.matchesPassphrase('nope'), isFalse);
    });

    test('HELLO_ACK carries the salt and survives a JSON round trip', () {
      final ack = DshHelloAck(
        ok: true,
        server: 'dsh-relay',
        version: '1.0.0',
        salt: Hex.decode('0f1e2d3c4b5a69788796a5b4c3d2e1f0'),
        nonce: Hex.decode('ffeeddccbbaa99887766554433221100'),
      );
      final parsed = DshHelloAck.parse(ack.encode());
      expect(parsed.ok, isTrue);
      expect(parsed.server, 'dsh-relay');
      expect(parsed.version, '1.0.0');
      expect(Hex.encode(parsed.salt), '0f1e2d3c4b5a69788796a5b4c3d2e1f0');
      expect(Hex.encode(parsed.nonce), 'ffeeddccbbaa99887766554433221100');
    });
  });

  group('helpers', () {
    test('hex round trips and rejects bad input', () {
      expect(Hex.encode([0x00, 0x0f, 0xff]), '000fff');
      expect(Hex.decode('000FFF'), [0x00, 0x0f, 0xff]);
      expect(() => Hex.decode('abc'), throwsFormatException);
      expect(() => Hex.decode('zz'), throwsFormatException);
    });

    test('constant time equality compares content, not identity', () {
      expect(constantTimeEquals([1, 2, 3], [1, 2, 3]), isTrue);
      expect(constantTimeEquals([1, 2, 3], [1, 2, 4]), isFalse);
      expect(constantTimeEquals([1, 2, 3], [1, 2]), isFalse);
    });
  });
}
